TrajectoryPlannerROS:
  max_vel_x: 0.5         
  min_vel_x: 0.1

  max_vel_y: 0.1         
  min_vel_y: 0.05

  max_vel_theta: 0.8    
  min_in_place_vel_theta: 0.4

  acc_lim_x: 0.5         
  acc_lim_y: 0.5
  acc_lim_theta: 1

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.2 
  latch_xy_goal_tolerance: true

  holonomic_robot: true
