obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.32, 0.14],
            [0.32, -0.14],
            [-0.32, -0.14],
            [-0.32, 0.14]]

inflation_radius: 0.1

plugins:
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  # - {name: static_layer, type: "costmap_2d::StaticLayer"} 


observation_sources: laser_scan_sensor  point_cloud_sensor

laser_scan_sensor: {sensor_frame: rslidar, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
point_cloud_sensor: {sensor_frame: rslidar, data_type: PointCloud2, topic: /rslidar_points_stamped, marking: true, clearing: true}
